# -*- coding: utf-8 -*-
"""final_subscriber_sum.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cIIoRDxWIgU_7n4mS7bbwqs0qdhNLk2v
"""

import rospy
from std_msgs.msg import Int64

def callback(data):
    # ทำสิ่งที่ต้องการกับข้อมูลที่รับเข้ามา
    rospy.loginfo("Received: %d", data.data)

def listener():
    rospy.init_node('listener', anonymous=True)
    rospy.Subscriber("/sum_std_id", Int64, callback)
    rospy.spin()

if __name__ == '__main__':
    listener()