# -*- coding: utf-8 -*-
"""final_server_surname.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cIIoRDxWIgU_7n4mS7bbwqs0qdhNLk2v
"""

import rospy
from std_srvs.srv import Empty

def handle_request(req):
   
    last_name = "<ทักษิณ ศิริแก้วเลิศ>"
    rospy.loginfo("Hi, My name is %s", last_name)
    return []

def service_server():
    rospy.init_node('service_server')
    rospy.Service('/hi_sur', Empty, handle_request)
    rospy.loginfo("Service server is ready.")
    rospy.spin()

if __name__ == '__main__':
    service_server()