# -*- coding: utf-8 -*-
"""final_client_surname.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cIIoRDxWIgU_7n4mS7bbwqs0qdhNLk2v
"""

import rospy
from std_srvs.srv import Empty

def call_service():
    rospy.wait_for_service('/hi_sur')
    try:
        hi_sur_proxy = rospy.ServiceProxy('/hi_sur', Empty)
        response = hi_sur_proxy()
        rospy.loginfo("Service response: %s", response)
    except rospy.ServiceException as e:
        rospy.logerr("Service call failed: %s", e)

if __name__ == '__main__':
    rospy.init_node('service_client')
    call_service()