# -*- coding: utf-8 -*-
"""final_publish_sum.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cIIoRDxWIgU_7n4mS7bbwqs0qdhNLk2v
"""

import rospy
from std_msgs.msg import Int64

def publish_sum_std_id():
    pub = rospy.Publisher('/sum_std_id', Int64, queue_size=10)
    
    std_id = 6352500455
    
    sum_std_id = sum([int(digit) for digit in str(std_id)])
    
    msg = Int64()
    msg.data = sum_std_id
  
    rospy.sleep(1)
    
    pub.publish(msg)
    
    rospy.loginfo("Published sum_std_id: %d", sum_std_id)

if __name__ == '__main__':
   
    rospy.init_node('sum_std_id_publisher', anonymous=True)
    
    
    publish_sum_std_id()