# -*- coding: utf-8 -*-
"""sort_object_y.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cIIoRDxWIgU_7n4mS7bbwqs0qdhNLk2v
"""

obj_detected = {'bottle': [110, 30], 'glass': [60, 35], 'book': [310, 23], 'phone': [90, 33], 'dice': [155, 38], 'mouse':
[200, 45], 'keyboard': [298, 65], 'fan': [300, 36]}

y = dict(sorted(obj_detected.items(), key=lambda item: item[1]))
print(y)